### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by LotJen** [Dropelikeit/laravel-jms-serializer#29]
Hi,

after executing "composer require dropelikeit/laravel-jms-serializer" the following error occurs:

dropelikeit/laravel-jms-serializer v4.0.0 requires illuminate/http ^8.0|^9.0 -> found illuminate/http[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.5] but these were not loaded, likely because it conflicts with another require.

Laravel version 10.7.1 is installed.

Please help.
Thanks.

**Comment by Dropelikeit** [comment]
Hi @LotJen, 

thank you for reporting this issue. This package doesn't currently support Laravel v10. I will release v5 with Laravel 10 support tomorrow morning (04/14/2023 around 10am).

Thank you to using this package! :)

**Comment by Dropelikeit** [comment]
Hi @LotJen,

I have now released the update to make this package work with Laravel 10. Unfortunately there is a dependency conflict between Laravel version 10 and the JMS/Serializer package.

I have already created a ticket to resolve it in the JMS-Serializer repository. Now unfortunately we have to wait until it is resolved.
https://github.com/schmittjoh/serializer/issues/1482

I apologize for the inconvenience.

**Comment by LotJen** [comment]
Hi @Dropelikeit,

thank you very much for your very quick reply.

**Comment by Dropelikeit** [comment]
Hi @LotJen ,

I have talked to the developers of the JMS/Serializer package. You can install this package in your Laravel 10 app without any problems. Please use the `-W` (`--with-all-dependencies`) flag, it downgrade the installed `doctrine/lexer` package, so you can use laravel and the JMS/Serializer inside this package.

If you have any problems or need help, do not hesitate to create a issue.

Thank you.

**Comment by LotJen** [comment]
Hi @Dropelikeit,

now it works like a charm.
Thanks very much.
